### ISSUE TITLE
dimension mismatch when calculate M1 matrix

### ISSUE THREAD

**Issue by OhGoodBird** [RyujiTamaki/SMN#1]
Hi,
i try to run train.py but i got the following error message

```
File "train.py", line 28, in build_SMN
    word_match = dot([context_word_embedding, response_word_embedding], axes=(3, 2))
ValueError: Dimension 1 in both shapes must be equal, but are 10 and 50 for 'dot_1/MatMul' (op: 'BatchMatMul') with input shapes: [?,10,50,200], [?,50,200,1]
```

python 2.7
tensorflow 1.4.1
keras 2.1.3

**Comment by WangFeng666** [comment]
@OhGoodBird @RyujiTamaki

**Comment by WangFeng666** [comment]
@OhGoodBird @RyujiTamaki

**Comment by WangFeng666** [comment]
@OhGoodBird @RyujiTamaki 
Hi,
I have encountered the same problem, did you have solved it?
thanks!

**Comment by OhGoodBird** [comment]
@WangFeng666
I changed keras backend from TF to Theano. Sorry I forgot which theano version I used.

**Comment by WangFeng666** [comment]
@OhGoodBird 
ok，i will have a try,thank you very much!

**Comment by RyujiTamaki** [comment]
@OhGoodBird @WangFeng666 
Sorry, I didn't notice this issue. Thank you @OhGoodBird !
